### ISSUE TITLE
Coups Critiques?Échecs Critiques?

### ISSUE THREAD

**Issue by BeBlob** [BeBlob/Projet_Java_L2S4#5]
J'ai une question pour vous les gars, est ce que vous voulez qu'on introduise un système de lancé de dès pour les dégâts? - Avec coups critiques et échecs critiques -

**Comment by sykoure** [comment]
Je propose une stat "agilité" pour ca, les coûts critiques se baseront dessus et pareil pour les échecs critiques (de toute facon dans tout les jeux la stat agilité est pété)

**Comment by BeBlob** [comment]
Ca va rendre le programme très compliqué ET ça ne nous rajoutera pas de points puisque ce n'est pas demandé :/
